ROLES = {
    "AE": {
        "label": "Account Executive",
        "icon": "💼",
        "description": "Own the business relationship and drive deal progression",
        "color": "#3b82f6",
        "context": (
            "Write for an Account Executive whose job is to own the business relationship and "
            "drive deal progression. Emphasize business value, ROI, customer outcomes, and how "
            "to surface pain and urgency in discovery conversations. Avoid deep technical "
            "implementation details — focus on what a buyer cares about and why they should act."
        ),
    },
    "SE": {
        "label": "Solution Engineer",
        "icon": "🔧",
        "description": "Own technical discovery, demos, and the path to technical win",
        "color": "#10b981",
        "context": (
            "Write for a Solution Engineer who owns technical discovery, product demonstrations, "
            "and POC execution. Emphasize architectural depth, technical differentiation, how to "
            "demonstrate capabilities to technical buyers, and how to connect technical features "
            "to business outcomes. Include architecture considerations and demo angles."
        ),
    },
    "ACE": {
        "label": "Account Cloud Engineer",
        "icon": "☁️",
        "description": "Own post-sale technical success and consumption growth",
        "color": "#f59e0b",
        "context": (
            "Write for an Account Cloud Engineer responsible for post-sale technical health, "
            "consumption growth, and expansion. Emphasize implementation patterns, performance "
            "optimization, consumption monitoring, and how to identify and activate expansion "
            "use cases within existing accounts."
        ),
    },
    "SDR": {
        "label": "Sales Development Rep",
        "icon": "📞",
        "description": "Prospect, qualify, and open doors for the field team",
        "color": "#8b5cf6",
        "context": (
            "Write for a Sales Development Representative focused on prospecting and "
            "qualification. Prioritize concise value pitches (30-second and 2-minute versions), "
            "top-of-funnel discovery questions, and conversation openers for specific personas. "
            "Keep technical depth minimal — focus on business outcomes, why to take a meeting, "
            "and how to qualify interest quickly."
        ),
    },
}

TOPICS = {
    "platform": {
        "label": "Snowflake Platform",
        "icon": "❄️",
        "color": "#29b5e8",
        "description": "Core architecture, compute, governance, security, and FinOps",
        "course_objective": "By the end of this course, you will be able to run a complete platform sales motion — from qualifying the right persona in the first 5 minutes, through a discovery conversation that surfaces real pain, to a scoped technical win ready for SE handoff.",
        "lessons": [
            {
                "id": 1,
                "title": "The Data Cloud — Why Snowflake",
                "subtitle": "Snowflake's vision, market position, and what makes it different",
                "duration": "7 min",
                "objectives": [
                    "Explain in two sentences why the Data Cloud matters to a VP of Data who has never heard of Snowflake",
                    "Describe the three problems Snowflake solves — cost, complexity, and data silos — in the customer's language, not Snowflake's",
                    "Distinguish Snowflake from a traditional data warehouse and a data lake when a prospect asks 'how is this different from what we have?'",
                ],
                "key_features": ["Data Cloud", "Snowgrid", "Multi-cloud delivery", "Marketplace"],
                "plt_keywords": ["Data Cloud", "platform", "multi-cloud", "Snowgrid", "marketplace"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Skeptical VP of Data",
                "scenario": "A prospect says: 'We already have Redshift. Give me the elevator pitch for why we'd consider switching.'",
            },
            {
                "id": 2,
                "title": "Snowflake Architecture",
                "subtitle": "Storage, compute, cloud services, and why separation matters",
                "duration": "8 min",
                "objectives": [
                    "Explain how Snowflake's three-layer architecture works to a data architect who asks why it's different from Redshift",
                    "Describe the business impact of separating storage from compute when a CFO asks why costs were lower than expected",
                    "Interpret a customer's cross-cloud requirement and explain how Snowgrid addresses it without over-engineering the answer",
                ],
                "key_features": ["Virtual Warehouses", "Micro-partitions", "Cloud Services Layer", "Snowgrid", "Apache Iceberg"],
                "plt_keywords": ["virtual warehouse", "architecture", "micro-partition", "cloud services", "Iceberg", "Snowgrid"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Data Platform Architect",
                "scenario": "A data architect asks: 'Walk me through how Snowflake's architecture differs from a traditional MPP data warehouse.'",
            },
            {
                "id": 3,
                "title": "Core Capabilities & Workloads",
                "subtitle": "What you can build and run on Snowflake",
                "duration": "8 min",
                "objectives": [
                    "Map a customer's stated workload type to the specific Snowflake capability area that addresses it, without defaulting to a generic platform pitch",
                    "Demonstrate in a 2-minute overview how Snowflake spans warehousing, engineering, and AI workloads for a CTO who asks 'what can you actually do for us?'",
                    "Apply a problem-to-capability mapping to redirect a stalled feature conversation back to customer outcomes",
                ],
                "key_features": ["Modern Compute", "Managed Services", "Governance", "Observability", "FinOps", "AI/ML"],
                "plt_keywords": ["workload", "analytics", "AI", "data engineering", "data lake", "governance"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "CTO",
                "scenario": "A CTO asks: 'Give me a 2-minute map of everything Snowflake can do for us.'",
            },
            {
                "id": 4,
                "title": "Governance, Security & Compliance",
                "subtitle": "Horizon Catalog, data masking, RBAC, and Trust Center",
                "duration": "9 min",
                "objectives": [
                    "Apply Snowflake's unified governance story to counter a CISO who says 'we manage governance in a separate tool'",
                    "Demonstrate how column-level security, row-level security, and data masking work together to satisfy a specific GDPR or HIPAA requirement",
                    "Use the Trust Center to answer a security audit question without escalating to engineering",
                ],
                "key_features": ["Horizon Catalog", "Data Masking", "Row-Level Security", "RBAC", "Trust Center", "Data Clean Rooms"],
                "plt_keywords": ["Horizon Catalog", "governance", "masking", "row access policy", "Trust Center", "RBAC", "classification"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "CISO",
                "scenario": "A CISO says: 'We have GDPR and HIPAA obligations. Show me how Snowflake handles access control and data protection.'",
            },
            {
                "id": 5,
                "title": "FinOps & Consumption Management",
                "subtitle": "Consumption pricing, cost visibility, and spend governance",
                "duration": "7 min",
                "objectives": [
                    "Explain Snowflake's consumption-based pricing to a CFO in 60 seconds without mentioning credits",
                    "Show a finance leader which tools — Resource Monitors, Budgets, and Account Usage views — map to their specific cost governance requirements",
                    "Apply a TCO framework to reframe the 'Snowflake is expensive' objection using cost attribution data, not list price",
                ],
                "key_features": ["Cost Management in Snowsight", "Resource Monitors", "Budgets", "Account Usage Views", "Auto-suspend"],
                "plt_keywords": ["FinOps", "cost management", "resource monitor", "budgets", "consumption", "ACCOUNT_USAGE", "auto-suspend"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "CFO",
                "scenario": "A CFO asks: 'How do we make sure Snowflake spend doesn't spiral out of control — and how is this different from our AWS bill?'",
            },
            {
                "id": 6,
                "title": "Platform Discovery & Sales Motion",
                "subtitle": "Personas, discovery questions, and the platform sales motion",
                "duration": "8 min",
                "objectives": [
                    "Identify which platform buyer persona (CDO, VP Engineering, Data Architect) is in the room within the first 5 minutes and adjust your opener accordingly",
                    "Apply three discovery questions that surface data architecture pain without defaulting to a feature demo",
                    "Execute the first-call-to-technical-win motion for a platform deal, from problem framing through the handoff to the SE",
                ],
                "key_features": ["Discovery Framework", "Platform Personas", "Competitive Traps", "Value Story"],
                "plt_keywords": ["platform", "discovery", "architecture", "migration", "modernization"],
                "bloom_level": "Apply",
                "domain_tag": "Technical Discovery & Value Selling",
                "coach_persona": "SE Manager",
                "scenario": "You have a first call with a VP of Data Engineering at a mid-market company. How do you open the discovery conversation?",
            },
        ],
    },

    "ai": {
        "label": "AI & Cortex",
        "icon": "🤖",
        "color": "#8b5cf6",
        "description": "Cortex AI, ML, intelligent agents, and AI-powered applications",
        "course_objective": "By the end of this course, you will be able to qualify an enterprise AI opportunity, differentiate Snowflake's AI approach against Databricks and OpenAI on governance and data gravity, and move a CDO from 'exploring AI' to a scoped proof of concept in a single call.",
        "lessons": [
            {
                "id": 1,
                "title": "AI at Snowflake — The Opportunity",
                "subtitle": "Why AI on your data platform is the winning bet",
                "duration": "7 min",
                "objectives": [
                    "Explain Snowflake's AI strategy — 'bring AI to the data, not data to the AI' — to a VP of Data Science who is skeptical about building AI inside a data platform",
                    "Describe the three enterprise AI challenges — governance, data readiness, and trust — using language a CDO would use in an all-hands meeting",
                    "Distinguish Cortex AI from OpenAI and Databricks AI on governance and data gravity, not just feature parity",
                ],
                "key_features": ["Cortex AI", "Snowflake Intelligence", "AI Data Cloud", "Trusted AI"],
                "plt_keywords": ["Cortex AI", "AI", "LLM", "machine learning", "artificial intelligence", "Snowflake Intelligence"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "VP of Data Science",
                "scenario": "A VP of Data Science says: 'We're already using OpenAI. Why do we need AI capabilities inside Snowflake?'",
            },
            {
                "id": 2,
                "title": "Cortex AI — Language & Generation",
                "subtitle": "LLMs, summarization, classification, and text intelligence",
                "duration": "9 min",
                "objectives": [
                    "Apply the correct Cortex AI function (COMPLETE, SUMMARIZE, CLASSIFY, EXTRACT, SENTIMENT) to a customer's stated business problem without pitching the full function suite",
                    "Demonstrate how Cortex AI runs inference in-place, without data egress, to counter a 'we just send data to OpenAI' objection",
                    "Map three real customer use cases — contract intelligence, support automation, document processing — to the specific Cortex function that solves each one",
                ],
                "key_features": ["AI_COMPLETE", "AI_SUMMARIZE", "AI_CLASSIFY", "AI_EXTRACT", "AI_SENTIMENT", "AI_FILTER"],
                "plt_keywords": ["Cortex Complete", "AI_COMPLETE", "AI_SUMMARIZE", "AI_CLASSIFY", "AI_EXTRACT", "AI_SENTIMENT", "Cortex functions"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Data Engineer",
                "scenario": "A data engineer asks: 'Show me how I'd classify 10 million support tickets by sentiment without spinning up a separate ML platform.'",
            },
            {
                "id": 3,
                "title": "Cortex ML — Prediction & Classification",
                "subtitle": "No-code ML for forecasting, anomaly detection, and classification",
                "duration": "8 min",
                "objectives": [
                    "Demonstrate Cortex ML Forecast as a no-code solution to a retail analytics lead who doesn't have a dedicated data science team",
                    "Apply Forecast, Anomaly Detection, and Classification to three different customer industry scenarios to show breadth without overwhelming the buyer",
                    "Choose between Cortex ML Functions and Snowpark ML based on a customer's stated technical resources and workload complexity",
                ],
                "key_features": ["Cortex ML Forecast", "Cortex ML Anomaly Detection", "Cortex ML Classification", "Snowpark ML"],
                "plt_keywords": ["Cortex ML", "forecast", "anomaly detection", "classification", "Snowpark ML", "machine learning functions"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Analytics Lead",
                "scenario": "A retail analytics lead asks: 'We want to forecast inventory demand. Can Snowflake do that without a dedicated data science team?'",
            },
            {
                "id": 4,
                "title": "Snowflake Intelligence & Agents",
                "subtitle": "AI agents, Cortex Search, and the agentic data experience",
                "duration": "9 min",
                "objectives": [
                    "Explain Snowflake Intelligence to a CDO who asks 'what's your answer to natural language analytics?' in under 2 minutes",
                    "Apply the Cortex Analyst + Cortex Search framing to a customer whose analysts are spending half their day writing SQL",
                    "Construct a scenario that demonstrates why Cortex Agents is the right answer for multi-step enterprise workflows versus a single-turn LLM call",
                ],
                "key_features": ["Snowflake Intelligence", "Cortex Analyst", "Cortex Search", "Cortex Agents"],
                "plt_keywords": ["Snowflake Intelligence", "Cortex Analyst", "Cortex Search", "Cortex Agents", "agentic", "semantic model"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Chief Data Officer",
                "scenario": "A CDO asks: 'My analysts spend all day writing SQL. What's the Snowflake answer to natural language analytics?'",
            },
            {
                "id": 5,
                "title": "AI Personas, Discovery & Sales Motion",
                "subtitle": "Who buys AI, what they care about, and how to sell it",
                "duration": "8 min",
                "objectives": [
                    "Identify within the first two questions whether an AI prospect is at the 'exploring' or 'building' maturity stage, and adjust the discovery path accordingly",
                    "Apply five AI discovery questions to uncover a customer's current AI stack, data readiness, and governance gaps",
                    "Execute the AI pilot-to-production motion: get from a CDO saying 'we're exploring AI' to a scoped proof of concept in a single call",
                ],
                "key_features": ["AI Discovery Questions", "AI Personas", "AI Sales Motion", "Pilot to Production"],
                "plt_keywords": ["Cortex AI", "AI", "LLM", "discovery", "machine learning"],
                "bloom_level": "Apply",
                "domain_tag": "Technical Discovery & Value Selling",
                "coach_persona": "Field AE",
                "scenario": "You're in a first meeting and the CDO mentions they're 'exploring AI.' How do you run a discovery conversation to qualify the AI opportunity?",
            },
            {
                "id": 6,
                "title": "AI Competitive Intelligence",
                "subtitle": "How to win AI deals against Databricks, Azure, and SageMaker",
                "duration": "7 min",
                "objectives": [
                    "Differentiate Snowflake's AI approach from Databricks across three dimensions — governance, data gravity, and deployment simplicity — without using Snowflake marketing language",
                    "Deconstruct a competitor's AI pitch to identify the one or two claims that don't hold at enterprise scale, then redirect the conversation",
                    "Analyze a customer's stated AI concern (cost, governance, vendor lock-in) and select the Snowflake counter-argument most likely to resonate with that specific buyer",
                ],
                "key_features": ["Competitive Battlecards", "Databricks AI Comparison", "Governance Differentiation", "Data Gravity"],
                "plt_keywords": ["Cortex AI", "AI governance", "LLM", "competitive", "Databricks"],
                "bloom_level": "Analyze",
                "domain_tag": "POC Execution & Getting the Technical Win",
                "coach_persona": "Competitive SE",
                "scenario": "A prospect says: 'Databricks has better AI tooling. Why would we use Snowflake for AI?' How do you respond?",
            },
        ],
    },

    "analytics": {
        "label": "Analytics",
        "icon": "📊",
        "color": "#f59e0b",
        "description": "Snowsight, Cortex Analyst, and the partner BI ecosystem",
        "course_objective": "By the end of this course, you will be able to sell an analytics modernization motion — from surfacing slow dashboards and BI sprawl through a targeted Snowsight or Cortex Analyst demo, to a value story the analytics champion can take to their CFO.",
        "lessons": [
            {
                "id": 1,
                "title": "Analytics at Snowflake — Overview",
                "subtitle": "From SQL to self-service to AI-powered analytics",
                "duration": "6 min",
                "objectives": [
                    "Summarize Snowflake's analytics evolution — SQL editor to self-service to natural language — to a Head of Analytics who asks 'what has Snowflake added in the last 2 years?'",
                    "Describe the three analytics buyer types (SQL analyst, business user, executive) and what each one needs from a platform",
                    "Distinguish Snowflake as a unified analytics platform from the 'we already have a BI tool' objection without dismissing the tool they use",
                ],
                "key_features": ["Snowsight", "Cortex Analyst", "Semantic Models", "Partner BI"],
                "plt_keywords": ["analytics", "Snowsight", "BI", "Cortex Analyst", "dashboards", "visualization"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Head of Analytics",
                "scenario": "A Head of Analytics asks: 'We already have Tableau. What does Snowflake add to our analytics stack?'",
            },
            {
                "id": 2,
                "title": "Snowsight — Native Analytics",
                "subtitle": "Dashboards, notebooks, and the unified Snowflake UI",
                "duration": "8 min",
                "objectives": [
                    "Demonstrate which Snowsight capability (dashboards, notebooks, SQL editor) fits a specific analyst workflow when asked 'what can I do without leaving Snowflake?'",
                    "Apply the Snowsight vs. partner BI decision framework to recommend the right tool for a customer's stated use case and user type",
                    "Connect Snowsight's notebook and dashboard capabilities to the analyst self-service use case in a way that justifies not buying a separate BI license",
                ],
                "key_features": ["Snowsight Dashboards", "Snowflake Notebooks", "Streamlit in Snowflake", "SQL Editor"],
                "plt_keywords": ["Snowsight", "dashboards", "notebooks", "Streamlit", "SQL editor", "visualization"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Data Analyst",
                "scenario": "A data analyst says: 'I want to build dashboards without leaving Snowflake. What can I do natively?'",
            },
            {
                "id": 3,
                "title": "Cortex Analyst — Text-to-SQL",
                "subtitle": "Natural language analytics powered by semantic models",
                "duration": "8 min",
                "objectives": [
                    "Demonstrate how Cortex Analyst enables a business user to query sales data in plain English without any SQL knowledge",
                    "Explain the semantic model's role as a business translation layer — and why it makes Cortex Analyst more accurate than a generic text-to-SQL tool — to a skeptical data engineer",
                    "Apply the Cortex Analyst use case to a specific buyer (business analyst, finance team, or product manager) and articulate why their current workflow is failing them",
                ],
                "key_features": ["Cortex Analyst", "Semantic Model", "Semantic Views", "Text-to-SQL", "Snowflake Intelligence"],
                "plt_keywords": ["Cortex Analyst", "semantic model", "text-to-SQL", "natural language", "Snowflake Intelligence", "semantic views"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Business Analyst",
                "scenario": "A business analyst says: 'I need to ask questions about our sales data but I can't write SQL. Is there an answer in Snowflake?'",
            },
            {
                "id": 4,
                "title": "Partner BI Ecosystem",
                "subtitle": "Tableau, Power BI, Looker, and how Snowflake powers them all",
                "duration": "7 min",
                "objectives": [
                    "Explain why Snowflake sitting beneath a customer's existing BI tool is a feature, not a constraint — in one sentence a BI Director would use in a budget conversation",
                    "Describe the native connector advantage for the customer's stated BI stack (Tableau, Power BI, Looker, or ThoughtSpot) without disparaging the tool they already use",
                    "Interpret a 'we're standardizing on Power BI' statement as an expansion opportunity rather than a closed door",
                ],
                "key_features": ["Tableau Connector", "Power BI Connector", "Looker", "ThoughtSpot", "Partner Connect"],
                "plt_keywords": ["Tableau", "Power BI", "Looker", "BI", "partner connect", "connector", "ThoughtSpot"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "BI Director",
                "scenario": "A BI Director says: 'We're standardizing on Power BI. Does Snowflake play well with that, or do we have to choose?'",
            },
            {
                "id": 5,
                "title": "Analytics Discovery & Sales Motion",
                "subtitle": "How to qualify and sell analytics opportunities",
                "duration": "7 min",
                "objectives": [
                    "Apply three discovery questions that surface slow dashboard performance, stale data, and BI sprawl without leading the customer to the answer",
                    "Distinguish the analytics champion (Head of Analytics) from the economic buyer (CFO or VP of Data) and engage each differently in the same sales cycle",
                    "Execute the analytics sales motion — from stated problem through targeted demo to a value story the champion can take to their CFO",
                ],
                "key_features": ["Analytics Discovery Questions", "Analytics Personas", "BI Modernization Motion"],
                "plt_keywords": ["analytics", "BI", "Snowsight", "Cortex Analyst", "discovery"],
                "bloom_level": "Apply",
                "domain_tag": "Technical Discovery & Value Selling",
                "coach_persona": "Field SE",
                "scenario": "You're meeting a Head of Analytics who says dashboards are slow and the BI team is overwhelmed. How do you run this discovery?",
            },
        ],
    },

    "data_engineering": {
        "label": "Data Engineering",
        "icon": "⚙️",
        "color": "#10b981",
        "description": "Pipelines, Snowpark, Dynamic Tables, and the modern data stack",
        "course_objective": "By the end of this course, you will be able to run a data engineering discovery conversation — identify pipeline fragility, tool sprawl, and cost pain, map each to a specific Snowflake capability, and close on a technical win proposal.",
        "lessons": [
            {
                "id": 1,
                "title": "Data Engineering at Snowflake",
                "subtitle": "Why Snowflake is where data engineers choose to build",
                "duration": "6 min",
                "objectives": [
                    "Describe Snowflake's full data engineering stack — ingest, transform, orchestrate, serve — to a data engineer who thinks of Snowflake as just a warehouse",
                    "Explain what a data engineering buyer prioritizes (developer experience, reliability, cost) versus what an analytics buyer cares about, and why that changes your pitch",
                    "Interpret a 'we use dbt and Airflow' statement and map each tool to the Snowflake native equivalent without dismissing the customer's current investment",
                ],
                "key_features": ["Snowpipe", "Streams & Tasks", "Dynamic Tables", "Snowpark", "Openflow"],
                "plt_keywords": ["data engineering", "pipeline", "ETL", "ELT", "Snowpark", "orchestration", "Snowpipe"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Data Engineering Lead",
                "scenario": "A data engineer says: 'We use dbt and Airflow. Why would I want to move my pipelines into Snowflake?'",
            },
            {
                "id": 2,
                "title": "Data Ingestion — Snowpipe & Connectors",
                "subtitle": "Getting data in: batch, streaming, and CDC",
                "duration": "8 min",
                "objectives": [
                    "Apply the right ingestion pattern (Snowpipe, Snowpipe Streaming, or Openflow) to a customer's stated data source and latency requirement",
                    "Demonstrate how Openflow handles CDC from a Postgres or Oracle source to answer 'we need near-real-time data without building a custom connector'",
                    "Map three customer ingestion scenarios — batch, streaming, CDC — to the specific Snowflake capability that handles each one",
                ],
                "key_features": ["Snowpipe", "Snowpipe Streaming", "Openflow", "Kafka Connector", "Change Data Capture"],
                "plt_keywords": ["Snowpipe", "Snowpipe Streaming", "Openflow", "Kafka", "CDC", "ingestion", "replication"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Platform Engineer",
                "scenario": "A platform engineer says: 'We need near-real-time data from our Postgres database into our analytics layer. What does that look like in Snowflake?'",
            },
            {
                "id": 3,
                "title": "Pipelines — Streams, Tasks & Dynamic Tables",
                "subtitle": "Declarative and event-driven data transformation at scale",
                "duration": "9 min",
                "objectives": [
                    "Show how Streams detect table changes and feed a downstream Task without Airflow or a separate orchestrator, using a real pipeline scenario",
                    "Apply the Streams + Tasks pattern to an incremental pipeline use case where the customer is currently running expensive full refreshes",
                    "Position Dynamic Tables as the answer when a customer asks 'how do I build a pipeline that just stays current?' versus manually scheduled Tasks",
                ],
                "key_features": ["Streams", "Tasks", "Dynamic Tables", "DAG Orchestration", "Incremental Processing"],
                "plt_keywords": ["Streams", "Tasks", "Dynamic Tables", "pipeline", "orchestration", "incremental", "DAG"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Data Engineer",
                "scenario": "A data engineer asks: 'We're building an incremental pipeline. How does Snowflake handle orchestration without Airflow?'",
            },
            {
                "id": 4,
                "title": "Snowpark — The Developer Platform",
                "subtitle": "Python, Java, Scala, and code-first data engineering on Snowflake",
                "duration": "9 min",
                "objectives": [
                    "Demonstrate Snowpark's Python DataFrame API as the reason a Python engineer doesn't need to pull data out of Snowflake to do complex transformations",
                    "Apply the Snowpark + Notebooks story to a customer who uses Jupyter notebooks and wants to run ML training on Snowflake data without a separate platform",
                    "Choose between Snowpark, Notebooks, and Snowpark Container Services based on the complexity and deployment requirements of a customer's stated workload",
                ],
                "key_features": ["Snowpark Python", "Snowpark DataFrame API", "Snowflake Notebooks", "Snowpark Container Services", "UDFs"],
                "plt_keywords": ["Snowpark", "Python", "DataFrame API", "UDF", "notebooks", "container services", "SPCS"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Senior Data Engineer",
                "scenario": "A senior data engineer says: 'I like Python. How do I build data pipelines in Snowflake without pulling data out?'",
            },
            {
                "id": 5,
                "title": "Data Engineering Discovery & Sales Motion",
                "subtitle": "How to qualify and sell data engineering opportunities",
                "duration": "7 min",
                "objectives": [
                    "Identify the data engineering champion's top pain signal — pipeline fragility, cost, or developer velocity — within the first two minutes and pivot the discovery accordingly",
                    "Apply five discovery questions that surface pipeline complexity and tool sprawl without pitching Snowflake prematurely",
                    "Execute the DE sales motion from complexity → simplification → targeted demo, culminating in a technical win proposal the SE can take forward",
                ],
                "key_features": ["DE Discovery Questions", "DE Personas", "Pipeline Modernization Motion"],
                "plt_keywords": ["data engineering", "pipeline", "Snowpark", "Dynamic Tables", "competitive"],
                "bloom_level": "Apply",
                "domain_tag": "Technical Discovery & Value Selling",
                "coach_persona": "Field SE",
                "scenario": "A VP of Engineering says: 'We're evaluating Snowflake and Databricks for our data platform. Walk me through your data engineering story.'",
            },
        ],
    },

    "apps_collab": {
        "label": "Apps & Collaboration",
        "icon": "🤝",
        "color": "#f97316",
        "description": "Marketplace, Native Apps, data sharing, and the collaboration ecosystem",
        "course_objective": "By the end of this course, you will be able to identify the right collaboration or app platform opportunity — data monetization, partner sharing, or native app distribution — and run a sales motion that ends with a framing the customer's product team will fund.",
        "lessons": [
            {
                "id": 1,
                "title": "The Data Cloud Ecosystem",
                "subtitle": "Collaboration, sharing, and the network that makes data more valuable",
                "duration": "7 min",
                "objectives": [
                    "Explain the Data Cloud as a network effect — not just a platform — to a CDO who asks 'what makes this different from just being a cloud data warehouse?'",
                    "Describe how Snowflake Marketplace enables live data and app sharing without building an API or moving data, in language a product team would understand",
                    "Distinguish Snowflake's collaboration story from a 'data sharing feature' into a strategic network moat argument a CDO would take to a board meeting",
                ],
                "key_features": ["Snowflake Marketplace", "Data Cloud Network", "Data Sharing", "Snowgrid"],
                "plt_keywords": ["Marketplace", "Data Cloud", "collaboration", "data sharing", "network", "ecosystem"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Chief Data Officer",
                "scenario": "A CDO asks: 'What do you mean by Data Cloud? Isn't Snowflake just a data warehouse?'",
            },
            {
                "id": 2,
                "title": "Snowflake Marketplace",
                "subtitle": "Live data, applications, and the world's largest data network",
                "duration": "8 min",
                "objectives": [
                    "Apply the data product vs. app product distinction to a customer's specific scenario — provider or consumer — without over-complicating the Marketplace pitch",
                    "Demonstrate the Powered-by Snowflake value proposition to a SaaS exec who wants to distribute product data to customers without building an API",
                    "Connect a customer's stated data monetization goal to the Marketplace listing model in a way the product team, not just the data team, would fund",
                ],
                "key_features": ["Snowflake Marketplace", "Powered-by Snowflake", "Data Products", "App Listings", "Data Monetization"],
                "plt_keywords": ["Marketplace", "Powered-by Snowflake", "ISV", "data products", "listings", "monetization"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Product Executive",
                "scenario": "A SaaS company exec asks: 'We want to distribute product data to customers without building an API. How would Marketplace work for us?'",
            },
            {
                "id": 3,
                "title": "Native Application Framework",
                "subtitle": "Building and distributing apps that run inside customer Snowflake accounts",
                "duration": "9 min",
                "objectives": [
                    "Demonstrate the Native App model to an ISV architect using its key differentiator — the app runs inside the customer's account, so the ISV never sees the customer's data",
                    "Apply the security and governance advantages of the native app model to counter an enterprise customer's concern about data leaving their environment",
                    "Distinguish the ISV builder use case from the customer consumption use case and identify which one applies to the person you're talking to within the first two questions",
                ],
                "key_features": ["Native App Framework", "Application Packages", "Snowpark Container Services", "Streamlit in Snowflake"],
                "plt_keywords": ["Native App Framework", "application package", "SPCS", "Streamlit", "native application"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "ISV Solutions Architect",
                "scenario": "An ISV architect asks: 'We want to build an app that runs on customer data without us ever seeing it. Is that possible in Snowflake?'",
            },
            {
                "id": 4,
                "title": "Data Sharing & Collaboration",
                "subtitle": "Secure, live data sharing without copying or ETL",
                "duration": "7 min",
                "objectives": [
                    "Demonstrate how Secure Data Sharing works — zero-copy, no ETL, governed — to a Head of Data Partnerships who is currently sharing data via file drops or FTP",
                    "Apply the Data Clean Rooms use case to a specific industry scenario (financial services, advertising, or healthcare) where the customer cannot share raw data directly",
                    "Map the data sharing capability to a named customer problem in a prospect's industry that they would recognize from their own experience",
                ],
                "key_features": ["Secure Data Sharing", "Data Clean Rooms", "Cross-cloud Sharing", "Snowgrid"],
                "plt_keywords": ["data sharing", "Data Clean Rooms", "secure sharing", "collaboration", "cross-cloud", "Snowgrid"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Head of Data Partnerships",
                "scenario": "A Head of Data Partnerships asks: 'We want to share real-time data with distribution partners without giving them direct database access. What does that look like?'",
            },
            {
                "id": 5,
                "title": "Apps & Collaboration Discovery & Sales Motion",
                "subtitle": "How to qualify and sell collaboration and app platform deals",
                "duration": "7 min",
                "objectives": [
                    "Identify which buyer type (CDO, ISV/Product exec, or Head of Data Partnerships) is driving the conversation and shift to the discovery framework that matches their role",
                    "Apply four discovery questions that surface data distribution pain, API complexity, and monetization goals without leading with the product",
                    "Execute the Apps & Collaboration sales motion from identified pain to a Marketplace listing or Native App framing that the customer's product team would fund",
                ],
                "key_features": ["Apps Discovery Questions", "Collaboration Personas", "Marketplace Sales Motion", "ISV Motion"],
                "plt_keywords": ["Marketplace", "collaboration", "data sharing", "Native App", "discovery"],
                "bloom_level": "Apply",
                "domain_tag": "Technical Discovery & Value Selling",
                "coach_persona": "Strategic Account AE",
                "scenario": "A media company's Head of Digital says they're sitting on valuable audience data they can't monetize. How do you take this discovery conversation forward?",
            },
        ],
    },
}

BLOOM_COLORS = {
    "Remember": "#94a3b8",
    "Understand": "#60a5fa",
    "Apply": "#34d399",
    "Analyze": "#f59e0b",
    "Evaluate": "#f97316",
    "Create": "#a78bfa",
}

COURSE_META = {
    "title": "Snowflake Sales Learning Engine",
    "subtitle": "Living Course · Role-Personalized",
    "total_topics": 5,
    "total_lessons": sum(len(t["lessons"]) for t in TOPICS.values()),
    "audience": "AE, SE, ACE, SDR",
    "level": "100",
}
