ROLES = {
    "AE": {
        "label": "Account Executive",
        "icon": "💼",
        "description": "Own the business relationship and drive deal progression",
        "color": "#3b82f6",
        "context": (
            "Write for an Account Executive whose job is to own the business relationship and "
            "drive deal progression. Emphasize business value, ROI, customer outcomes, and how "
            "to surface pain and urgency in discovery conversations. Avoid deep technical "
            "implementation details — focus on what a buyer cares about and why they should act."
        ),
    },
    "SE": {
        "label": "Solution Engineer",
        "icon": "🔧",
        "description": "Own technical discovery, demos, and the path to technical win",
        "color": "#10b981",
        "context": (
            "Write for a Solution Engineer who owns technical discovery, product demonstrations, "
            "and POC execution. Emphasize architectural depth, technical differentiation, how to "
            "demonstrate capabilities to technical buyers, and how to connect technical features "
            "to business outcomes. Include architecture considerations and demo angles."
        ),
    },
    "ACE": {
        "label": "Account Cloud Engineer",
        "icon": "☁️",
        "description": "Own post-sale technical success and consumption growth",
        "color": "#f59e0b",
        "context": (
            "Write for an Account Cloud Engineer responsible for post-sale technical health, "
            "consumption growth, and expansion. Emphasize implementation patterns, performance "
            "optimization, consumption monitoring, and how to identify and activate expansion "
            "use cases within existing accounts."
        ),
    },
    "SDR": {
        "label": "Sales Development Rep",
        "icon": "📞",
        "description": "Prospect, qualify, and open doors for the field team",
        "color": "#8b5cf6",
        "context": (
            "Write for a Sales Development Representative focused on prospecting and "
            "qualification. Prioritize concise value pitches (30-second and 2-minute versions), "
            "top-of-funnel discovery questions, and conversation openers for specific personas. "
            "Keep technical depth minimal — focus on business outcomes, why to take a meeting, "
            "and how to qualify interest quickly."
        ),
    },
}

TOPICS = {
    "platform": {
        "label": "Snowflake Platform",
        "icon": "❄️",
        "color": "#29b5e8",
        "description": "Core architecture, compute, governance, security, and FinOps",
        "lessons": [
            {
                "id": 1,
                "title": "The Data Cloud — Why Snowflake",
                "subtitle": "Snowflake's vision, market position, and what makes it different",
                "duration": "7 min",
                "objectives": [
                    "Articulate the Snowflake story and why the Data Cloud matters now",
                    "Explain the three core problems Snowflake solves: cost, complexity, and data silos",
                    "Position Snowflake against the data warehouse and data lake status quo",
                ],
                "key_features": ["Data Cloud", "Snowgrid", "Multi-cloud delivery", "Marketplace"],
                "plt_keywords": ["Data Cloud", "platform", "multi-cloud", "Snowgrid", "marketplace"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Skeptical VP of Data",
                "scenario": "A prospect says: 'We already have Redshift. Give me the elevator pitch for why we'd consider switching.'",
            },
            {
                "id": 2,
                "title": "Snowflake Architecture",
                "subtitle": "Storage, compute, cloud services, and why separation matters",
                "duration": "8 min",
                "objectives": [
                    "Explain Snowflake's three-layer architecture: storage, compute, cloud services",
                    "Describe the business value of separating storage from compute",
                    "Connect Snowgrid to cross-cloud and cross-region customer requirements",
                ],
                "key_features": ["Virtual Warehouses", "Micro-partitions", "Cloud Services Layer", "Snowgrid", "Apache Iceberg"],
                "plt_keywords": ["virtual warehouse", "architecture", "micro-partition", "cloud services", "Iceberg", "Snowgrid"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Data Platform Architect",
                "scenario": "A data architect asks: 'Walk me through how Snowflake's architecture differs from a traditional MPP data warehouse.'",
            },
            {
                "id": 3,
                "title": "Core Capabilities & Workloads",
                "subtitle": "What you can build and run on Snowflake",
                "duration": "8 min",
                "objectives": [
                    "Map Snowflake's capability areas to real customer workloads",
                    "Explain the difference between data warehousing, data engineering, and AI/ML workloads",
                    "Connect customer business problems to the right Snowflake capability",
                ],
                "key_features": ["Modern Compute", "Managed Services", "Governance", "Observability", "FinOps", "AI/ML"],
                "plt_keywords": ["workload", "analytics", "AI", "data engineering", "data lake", "governance"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "CTO",
                "scenario": "A CTO asks: 'Give me a 2-minute map of everything Snowflake can do for us.'",
            },
            {
                "id": 4,
                "title": "Governance, Security & Compliance",
                "subtitle": "Horizon Catalog, data masking, RBAC, and Trust Center",
                "duration": "9 min",
                "objectives": [
                    "Position Snowflake's unified governance model vs. fragmented competitors",
                    "Describe column-level security, row-level security, and data masking",
                    "Explain the Trust Center as a single security health dashboard",
                ],
                "key_features": ["Horizon Catalog", "Data Masking", "Row-Level Security", "RBAC", "Trust Center", "Data Clean Rooms"],
                "plt_keywords": ["Horizon Catalog", "governance", "masking", "row access policy", "Trust Center", "RBAC", "classification"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "CISO",
                "scenario": "A CISO says: 'We have GDPR and HIPAA obligations. Show me how Snowflake handles access control and data protection.'",
            },
            {
                "id": 5,
                "title": "FinOps & Consumption Management",
                "subtitle": "Consumption pricing, cost visibility, and spend governance",
                "duration": "7 min",
                "objectives": [
                    "Explain Snowflake's consumption-based pricing model to a non-technical buyer",
                    "Describe the tools available for cost attribution and spend governance",
                    "Position Snowflake's TCO vs. legacy alternatives",
                ],
                "key_features": ["Cost Management in Snowsight", "Resource Monitors", "Budgets", "Account Usage Views", "Auto-suspend"],
                "plt_keywords": ["FinOps", "cost management", "resource monitor", "budgets", "consumption", "ACCOUNT_USAGE", "auto-suspend"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "CFO",
                "scenario": "A CFO asks: 'How do we make sure Snowflake spend doesn't spiral out of control — and how is this different from our AWS bill?'",
            },
            {
                "id": 6,
                "title": "Platform Discovery & Sales Motion",
                "subtitle": "Personas, discovery questions, and the platform sales motion",
                "duration": "8 min",
                "objectives": [
                    "Identify the primary platform buyer personas and their pain points",
                    "Apply a discovery framework to surface data architecture pain",
                    "Navigate the platform sales motion from first call to technical win",
                ],
                "key_features": ["Discovery Framework", "Platform Personas", "Competitive Traps", "Value Story"],
                "plt_keywords": ["platform", "discovery", "architecture", "migration", "modernization"],
                "bloom_level": "Apply",
                "domain_tag": "Technical Discovery & Value Selling",
                "coach_persona": "SE Manager",
                "scenario": "You have a first call with a VP of Data Engineering at a mid-market company. How do you open the discovery conversation?",
            },
        ],
    },

    "ai": {
        "label": "AI & Cortex",
        "icon": "🤖",
        "color": "#8b5cf6",
        "description": "Cortex AI, ML, intelligent agents, and AI-powered applications",
        "lessons": [
            {
                "id": 1,
                "title": "AI at Snowflake — The Opportunity",
                "subtitle": "Why AI on your data platform is the winning bet",
                "duration": "7 min",
                "objectives": [
                    "Articulate Snowflake's AI strategy: bring AI to the data, not data to the AI",
                    "Explain the enterprise AI challenge: governance, data readiness, and trust",
                    "Position Cortex AI as the most governed, connected AI platform",
                ],
                "key_features": ["Cortex AI", "Snowflake Intelligence", "AI Data Cloud", "Trusted AI"],
                "plt_keywords": ["Cortex AI", "AI", "LLM", "machine learning", "artificial intelligence", "Snowflake Intelligence"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "VP of Data Science",
                "scenario": "A VP of Data Science says: 'We're already using OpenAI. Why do we need AI capabilities inside Snowflake?'",
            },
            {
                "id": 2,
                "title": "Cortex AI — Language & Generation",
                "subtitle": "LLMs, summarization, classification, and text intelligence",
                "duration": "9 min",
                "objectives": [
                    "Explain the Cortex AI function suite: COMPLETE, SUMMARIZE, CLASSIFY, EXTRACT, SENTIMENT",
                    "Describe how Cortex AI runs inference on data without moving it out of Snowflake",
                    "Connect Cortex AI to real use cases: contract intelligence, support automation, document processing",
                ],
                "key_features": ["AI_COMPLETE", "AI_SUMMARIZE", "AI_CLASSIFY", "AI_EXTRACT", "AI_SENTIMENT", "AI_FILTER"],
                "plt_keywords": ["Cortex Complete", "AI_COMPLETE", "AI_SUMMARIZE", "AI_CLASSIFY", "AI_EXTRACT", "AI_SENTIMENT", "Cortex functions"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Data Engineer",
                "scenario": "A data engineer asks: 'Show me how I'd classify 10 million support tickets by sentiment without spinning up a separate ML platform.'",
            },
            {
                "id": 3,
                "title": "Cortex ML — Prediction & Classification",
                "subtitle": "No-code ML for forecasting, anomaly detection, and classification",
                "duration": "8 min",
                "objectives": [
                    "Explain Cortex ML Functions as no-code ML for SQL users",
                    "Describe the three primary capabilities: Forecast, Anomaly Detection, Classification",
                    "Identify when to recommend Cortex ML vs. full ML pipelines in Snowpark",
                ],
                "key_features": ["Cortex ML Forecast", "Cortex ML Anomaly Detection", "Cortex ML Classification", "Snowpark ML"],
                "plt_keywords": ["Cortex ML", "forecast", "anomaly detection", "classification", "Snowpark ML", "machine learning functions"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Analytics Lead",
                "scenario": "A retail analytics lead asks: 'We want to forecast inventory demand. Can Snowflake do that without a dedicated data science team?'",
            },
            {
                "id": 4,
                "title": "Snowflake Intelligence & Agents",
                "subtitle": "AI agents, Cortex Search, and the agentic data experience",
                "duration": "9 min",
                "objectives": [
                    "Explain Snowflake Intelligence as the AI-powered analytics and agent platform",
                    "Describe Cortex Analyst and Cortex Search as the two foundation services",
                    "Position Cortex Agents for multi-step, tool-using AI workflows on enterprise data",
                ],
                "key_features": ["Snowflake Intelligence", "Cortex Analyst", "Cortex Search", "Cortex Agents"],
                "plt_keywords": ["Snowflake Intelligence", "Cortex Analyst", "Cortex Search", "Cortex Agents", "agentic", "semantic model"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Chief Data Officer",
                "scenario": "A CDO asks: 'My analysts spend all day writing SQL. What's the Snowflake answer to natural language analytics?'",
            },
            {
                "id": 5,
                "title": "AI Personas, Discovery & Sales Motion",
                "subtitle": "Who buys AI, what they care about, and how to sell it",
                "duration": "8 min",
                "objectives": [
                    "Identify the primary AI buyer personas: CDO, Data Science Lead, App Developer",
                    "Apply the AI discovery framework to surface AI maturity and readiness",
                    "Navigate the AI sales motion from pilot to production workload",
                ],
                "key_features": ["AI Discovery Questions", "AI Personas", "AI Sales Motion", "Pilot to Production"],
                "plt_keywords": ["Cortex AI", "AI", "LLM", "discovery", "machine learning"],
                "bloom_level": "Apply",
                "domain_tag": "Technical Discovery & Value Selling",
                "coach_persona": "Field AE",
                "scenario": "You're in a first meeting and the CDO mentions they're 'exploring AI.' How do you run a discovery conversation to qualify the AI opportunity?",
            },
            {
                "id": 6,
                "title": "AI Competitive Intelligence",
                "subtitle": "How to win AI deals against Databricks, Azure, and SageMaker",
                "duration": "7 min",
                "objectives": [
                    "Articulate Snowflake's top three AI differentiators vs. Databricks",
                    "Set competitive traps in AI discovery conversations",
                    "Position trusted, governed AI as a risk-reduction argument for enterprise buyers",
                ],
                "key_features": ["Competitive Battlecards", "Databricks AI Comparison", "Governance Differentiation", "Data Gravity"],
                "plt_keywords": ["Cortex AI", "AI governance", "LLM", "competitive", "Databricks"],
                "bloom_level": "Analyze",
                "domain_tag": "POC Execution & Getting the Technical Win",
                "coach_persona": "Competitive SE",
                "scenario": "A prospect says: 'Databricks has better AI tooling. Why would we use Snowflake for AI?' How do you respond?",
            },
        ],
    },

    "analytics": {
        "label": "Analytics",
        "icon": "📊",
        "color": "#f59e0b",
        "description": "Snowsight, Cortex Analyst, and the partner BI ecosystem",
        "lessons": [
            {
                "id": 1,
                "title": "Analytics at Snowflake — Overview",
                "subtitle": "From SQL to self-service to AI-powered analytics",
                "duration": "6 min",
                "objectives": [
                    "Explain Snowflake's analytics evolution: SQL → Snowsight → Cortex Analyst",
                    "Describe the analytics buyers and what they care about",
                    "Position Snowflake as the unified analytics platform vs. point solutions",
                ],
                "key_features": ["Snowsight", "Cortex Analyst", "Semantic Models", "Partner BI"],
                "plt_keywords": ["analytics", "Snowsight", "BI", "Cortex Analyst", "dashboards", "visualization"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Head of Analytics",
                "scenario": "A Head of Analytics asks: 'We already have Tableau. What does Snowflake add to our analytics stack?'",
            },
            {
                "id": 2,
                "title": "Snowsight — Native Analytics",
                "subtitle": "Dashboards, notebooks, and the unified Snowflake UI",
                "duration": "8 min",
                "objectives": [
                    "Describe Snowsight capabilities: dashboards, charts, notebooks, query editor",
                    "Explain when to recommend Snowsight vs. a partner BI tool",
                    "Connect Snowsight to the analyst self-service use case",
                ],
                "key_features": ["Snowsight Dashboards", "Snowflake Notebooks", "Streamlit in Snowflake", "SQL Editor"],
                "plt_keywords": ["Snowsight", "dashboards", "notebooks", "Streamlit", "SQL editor", "visualization"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Data Analyst",
                "scenario": "A data analyst says: 'I want to build dashboards without leaving Snowflake. What can I do natively?'",
            },
            {
                "id": 3,
                "title": "Cortex Analyst — Text-to-SQL",
                "subtitle": "Natural language analytics powered by semantic models",
                "duration": "8 min",
                "objectives": [
                    "Explain Cortex Analyst as a semantic layer enabling natural language queries",
                    "Describe the semantic model as the business translation layer between data and AI",
                    "Position Cortex Analyst for the business user who can't write SQL",
                ],
                "key_features": ["Cortex Analyst", "Semantic Model", "Semantic Views", "Text-to-SQL", "Snowflake Intelligence"],
                "plt_keywords": ["Cortex Analyst", "semantic model", "text-to-SQL", "natural language", "Snowflake Intelligence", "semantic views"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Business Analyst",
                "scenario": "A business analyst says: 'I need to ask questions about our sales data but I can't write SQL. Is there an answer in Snowflake?'",
            },
            {
                "id": 4,
                "title": "Partner BI Ecosystem",
                "subtitle": "Tableau, Power BI, Looker, and how Snowflake powers them all",
                "duration": "7 min",
                "objectives": [
                    "Explain Snowflake's role as the data platform that powers any BI tool",
                    "Describe the key partnerships with Tableau, Power BI, Looker, and ThoughtSpot",
                    "Position Snowflake's native partner connectors as a competitive advantage",
                ],
                "key_features": ["Tableau Connector", "Power BI Connector", "Looker", "ThoughtSpot", "Partner Connect"],
                "plt_keywords": ["Tableau", "Power BI", "Looker", "BI", "partner connect", "connector", "ThoughtSpot"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "BI Director",
                "scenario": "A BI Director says: 'We're standardizing on Power BI. Does Snowflake play well with that, or do we have to choose?'",
            },
            {
                "id": 5,
                "title": "Analytics Discovery & Sales Motion",
                "subtitle": "How to qualify and sell analytics opportunities",
                "duration": "7 min",
                "objectives": [
                    "Apply the analytics discovery framework to surface BI pain and data bottlenecks",
                    "Identify the analytics champion and the economic buyer",
                    "Navigate the analytics sales motion: problem → demo → value story",
                ],
                "key_features": ["Analytics Discovery Questions", "Analytics Personas", "BI Modernization Motion"],
                "plt_keywords": ["analytics", "BI", "Snowsight", "Cortex Analyst", "discovery"],
                "bloom_level": "Apply",
                "domain_tag": "Technical Discovery & Value Selling",
                "coach_persona": "Field SE",
                "scenario": "You're meeting a Head of Analytics who says dashboards are slow and the BI team is overwhelmed. How do you run this discovery?",
            },
        ],
    },

    "data_engineering": {
        "label": "Data Engineering",
        "icon": "⚙️",
        "color": "#10b981",
        "description": "Pipelines, Snowpark, Dynamic Tables, and the modern data stack",
        "lessons": [
            {
                "id": 1,
                "title": "Data Engineering at Snowflake",
                "subtitle": "Why Snowflake is where data engineers choose to build",
                "duration": "6 min",
                "objectives": [
                    "Position Snowflake as a full data engineering platform, not just a warehouse",
                    "Explain the data engineering buyer and what they prioritize: DX, reliability, cost",
                    "Map the data engineering stack: ingest → transform → orchestrate → serve",
                ],
                "key_features": ["Snowpipe", "Streams & Tasks", "Dynamic Tables", "Snowpark", "Openflow"],
                "plt_keywords": ["data engineering", "pipeline", "ETL", "ELT", "Snowpark", "orchestration", "Snowpipe"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Data Engineering Lead",
                "scenario": "A data engineer says: 'We use dbt and Airflow. Why would I want to move my pipelines into Snowflake?'",
            },
            {
                "id": 2,
                "title": "Data Ingestion — Snowpipe & Connectors",
                "subtitle": "Getting data in: batch, streaming, and CDC",
                "duration": "8 min",
                "objectives": [
                    "Describe Snowpipe and Snowpipe Streaming for continuous data ingestion",
                    "Explain Openflow for CDC and replication from operational systems",
                    "Connect ingestion patterns to real customer workload types",
                ],
                "key_features": ["Snowpipe", "Snowpipe Streaming", "Openflow", "Kafka Connector", "Change Data Capture"],
                "plt_keywords": ["Snowpipe", "Snowpipe Streaming", "Openflow", "Kafka", "CDC", "ingestion", "replication"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Platform Engineer",
                "scenario": "A platform engineer says: 'We need near-real-time data from our Postgres database into our analytics layer. What does that look like in Snowflake?'",
            },
            {
                "id": 3,
                "title": "Pipelines — Streams, Tasks & Dynamic Tables",
                "subtitle": "Declarative and event-driven data transformation at scale",
                "duration": "9 min",
                "objectives": [
                    "Explain Streams as a CDC mechanism for detecting table changes",
                    "Describe Tasks for pipeline orchestration without external schedulers",
                    "Position Dynamic Tables as the declarative, auto-refreshing transformation layer",
                ],
                "key_features": ["Streams", "Tasks", "Dynamic Tables", "DAG Orchestration", "Incremental Processing"],
                "plt_keywords": ["Streams", "Tasks", "Dynamic Tables", "pipeline", "orchestration", "incremental", "DAG"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Data Engineer",
                "scenario": "A data engineer asks: 'We're building an incremental pipeline. How does Snowflake handle orchestration without Airflow?'",
            },
            {
                "id": 4,
                "title": "Snowpark — The Developer Platform",
                "subtitle": "Python, Java, Scala, and code-first data engineering on Snowflake",
                "duration": "9 min",
                "objectives": [
                    "Explain Snowpark as the code-first developer experience for Snowflake",
                    "Describe the Snowpark DataFrame API and how it pushes compute to Snowflake",
                    "Position Snowflake Notebooks and Container Services for ML and custom workloads",
                ],
                "key_features": ["Snowpark Python", "Snowpark DataFrame API", "Snowflake Notebooks", "Snowpark Container Services", "UDFs"],
                "plt_keywords": ["Snowpark", "Python", "DataFrame API", "UDF", "notebooks", "container services", "SPCS"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Senior Data Engineer",
                "scenario": "A senior data engineer says: 'I like Python. How do I build data pipelines in Snowflake without pulling data out?'",
            },
            {
                "id": 5,
                "title": "Data Engineering Discovery & Sales Motion",
                "subtitle": "How to qualify and sell data engineering opportunities",
                "duration": "7 min",
                "objectives": [
                    "Identify the data engineering champion and the pain signals to listen for",
                    "Apply the data engineering discovery framework to surface pipeline complexity and cost",
                    "Navigate the DE sales motion from complexity → simplification → demo",
                ],
                "key_features": ["DE Discovery Questions", "DE Personas", "Pipeline Modernization Motion"],
                "plt_keywords": ["data engineering", "pipeline", "Snowpark", "Dynamic Tables", "competitive"],
                "bloom_level": "Apply",
                "domain_tag": "Technical Discovery & Value Selling",
                "coach_persona": "Field SE",
                "scenario": "A VP of Engineering says: 'We're evaluating Snowflake and Databricks for our data platform. Walk me through your data engineering story.'",
            },
        ],
    },

    "apps_collab": {
        "label": "Apps & Collaboration",
        "icon": "🤝",
        "color": "#f97316",
        "description": "Marketplace, Native Apps, data sharing, and the collaboration ecosystem",
        "lessons": [
            {
                "id": 1,
                "title": "The Data Cloud Ecosystem",
                "subtitle": "Collaboration, sharing, and the network that makes data more valuable",
                "duration": "7 min",
                "objectives": [
                    "Explain the Data Cloud as a network, not just a platform",
                    "Describe how Snowflake Marketplace enables live data and app sharing",
                    "Position the collaboration story as a strategic moat vs. point solutions",
                ],
                "key_features": ["Snowflake Marketplace", "Data Cloud Network", "Data Sharing", "Snowgrid"],
                "plt_keywords": ["Marketplace", "Data Cloud", "collaboration", "data sharing", "network", "ecosystem"],
                "bloom_level": "Understand",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Chief Data Officer",
                "scenario": "A CDO asks: 'What do you mean by Data Cloud? Isn't Snowflake just a data warehouse?'",
            },
            {
                "id": 2,
                "title": "Snowflake Marketplace",
                "subtitle": "Live data, applications, and the world's largest data network",
                "duration": "8 min",
                "objectives": [
                    "Explain the difference between data products and app products on the Marketplace",
                    "Describe the Powered-by Snowflake program for ISVs and SaaS builders",
                    "Connect Marketplace to the data monetization use case",
                ],
                "key_features": ["Snowflake Marketplace", "Powered-by Snowflake", "Data Products", "App Listings", "Data Monetization"],
                "plt_keywords": ["Marketplace", "Powered-by Snowflake", "ISV", "data products", "listings", "monetization"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Product Executive",
                "scenario": "A SaaS company exec asks: 'We want to distribute product data to customers without building an API. How would Marketplace work for us?'",
            },
            {
                "id": 3,
                "title": "Native Application Framework",
                "subtitle": "Building and distributing apps that run inside customer Snowflake accounts",
                "duration": "9 min",
                "objectives": [
                    "Explain the Native App Framework: apps that run inside customer accounts",
                    "Describe the security and governance advantages of the native app model",
                    "Identify the ISV/SaaS builder use case and the customer consumption use case",
                ],
                "key_features": ["Native App Framework", "Application Packages", "Snowpark Container Services", "Streamlit in Snowflake"],
                "plt_keywords": ["Native App Framework", "application package", "SPCS", "Streamlit", "native application"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "ISV Solutions Architect",
                "scenario": "An ISV architect asks: 'We want to build an app that runs on customer data without us ever seeing it. Is that possible in Snowflake?'",
            },
            {
                "id": 4,
                "title": "Data Sharing & Collaboration",
                "subtitle": "Secure, live data sharing without copying or ETL",
                "duration": "7 min",
                "objectives": [
                    "Explain Secure Data Sharing as zero-copy, live, governed data exchange",
                    "Describe Data Clean Rooms for privacy-preserving collaboration",
                    "Connect data sharing to FS, advertising, and healthcare use cases",
                ],
                "key_features": ["Secure Data Sharing", "Data Clean Rooms", "Cross-cloud Sharing", "Snowgrid"],
                "plt_keywords": ["data sharing", "Data Clean Rooms", "secure sharing", "collaboration", "cross-cloud", "Snowgrid"],
                "bloom_level": "Apply",
                "domain_tag": "Product & Platform Knowledge",
                "coach_persona": "Head of Data Partnerships",
                "scenario": "A Head of Data Partnerships asks: 'We want to share real-time data with distribution partners without giving them direct database access. What does that look like?'",
            },
            {
                "id": 5,
                "title": "Apps & Collaboration Discovery & Sales Motion",
                "subtitle": "How to qualify and sell collaboration and app platform deals",
                "duration": "7 min",
                "objectives": [
                    "Identify the three primary buyer personas: CDO, ISV/Product, Data Partnerships",
                    "Apply the collaboration discovery framework to surface data distribution and monetization pain",
                    "Navigate the Apps & Collaboration sales motion from problem to Marketplace listing",
                ],
                "key_features": ["Apps Discovery Questions", "Collaboration Personas", "Marketplace Sales Motion", "ISV Motion"],
                "plt_keywords": ["Marketplace", "collaboration", "data sharing", "Native App", "discovery"],
                "bloom_level": "Apply",
                "domain_tag": "Technical Discovery & Value Selling",
                "coach_persona": "Strategic Account AE",
                "scenario": "A media company's Head of Digital says they're sitting on valuable audience data they can't monetize. How do you take this discovery conversation forward?",
            },
        ],
    },
}

BLOOM_COLORS = {
    "Remember": "#94a3b8",
    "Understand": "#60a5fa",
    "Apply": "#34d399",
    "Analyze": "#f59e0b",
    "Evaluate": "#f97316",
    "Create": "#a78bfa",
}

COURSE_META = {
    "title": "Snowflake Sales Learning Engine",
    "subtitle": "Living Course · Role-Personalized",
    "total_topics": 5,
    "total_lessons": sum(len(t["lessons"]) for t in TOPICS.values()),
    "audience": "AE, SE, ACE, SDR",
    "level": "100",
}
